# Generated by Django 4.2.7 on 2024-01-07 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webScrappingTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacaoalvo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='informacaoalvo',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
