# Generated by Django 4.2.7 on 2024-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScrappingTask', '0002_remove_informacaoalvo_cliente_informacaoalvo_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaoalvo',
            name='codigo_acesso',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='informacaoalvo',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Processando', 'Processando'), ('Finalizado', 'Finalizado'), ('Error', 'Error')], default='Aguardando', max_length=11),
        ),
    ]
