version: "3.8"

services:
  localstack:
    container_name: local-aws
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=serverless,rds,sqs,sns,cloudformation
      - HOST_TMP_FOLDER=${TMPDIR}
    image: localstack/localstack:latest
    ports:
      - '53:53'
      - '443:443'
      - '4510-4520:4510-4520'
      - '4566-4620:4566-4620'
    volumes:
      - ${TMPDIR:-}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

