# Generated by Django 4.2.7 on 2024-01-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScrappingTask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskprocessing',
            old_name='proccesssing',
            new_name='processing',
        ),
        migrations.AlterField(
            model_name='targetsitedata',
            name='status_process',
            field=models.CharField(choices=[('A', 'Aguardando'), ('P', 'Processando'), ('F', 'Finalizado'), ('E', 'Error')], default='A', max_length=1),
        ),
    ]
