# Generated by Django 4.2.7 on 2024-01-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScrappingTask', '0002_rename_proccesssing_taskprocessing_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsitedata',
            name='url_file',
            field=models.URLField(blank=True),
        ),
    ]
